# vim:ft=kitty

## name: Tokyo Night
## license: popachcka-rulet
## author: an idiot
## upstream:  /////////gol


background #07090B
foreground #EEF7FD
selection_background #C1D6D6
selection_foreground #07090B
url_color #73daca
cursor #c0caf5
cursor_text_color #1a1b26

# Tabs
active_tab_background #C1D6D6
active_tab_foreground #25C39F
inactive_tab_background #5C6871
inactive_tab_foreground #07090B
#tab_bar_background #15161e

# Windows
active_border_color #25C39F
inactive_border_color #C0CAF5

# normal
color0 #07090B
color1 #FF0100
color2 #25C39F
color3 #FFDE00
color4 #109FFF
color5 #FE31FF
color6 #00FED4
color7 #EEF7FD

# bright
 color8  #5C6871
 color9 #E46468
 color10 #82D1B9
 color11 #F6DB8B
 color12 #8FD2F7
 color13 #F79DE7
 color14 #7EFEDE
 color15 #C1D6D6

# extended colors
color16 #ff9e64
color17 #db4b4b
